/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueriesRouteImport } from './routes/queries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueriesIdRouteImport } from './routes/queries.$id'
import { Route as HostsIdRouteImport } from './routes/hosts.$id'

const QueriesRoute = QueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesIdRoute = QueriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QueriesRoute,
} as any)
const HostsIdRoute = HostsIdRouteImport.update({
  id: '/hosts/$id',
  path: '/hosts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/queries': typeof QueriesRouteWithChildren
  '/hosts/$id': typeof HostsIdRoute
  '/queries/$id': typeof QueriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queries': typeof QueriesRouteWithChildren
  '/hosts/$id': typeof HostsIdRoute
  '/queries/$id': typeof QueriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/queries': typeof QueriesRouteWithChildren
  '/hosts/$id': typeof HostsIdRoute
  '/queries/$id': typeof QueriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/queries' | '/hosts/$id' | '/queries/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/queries' | '/hosts/$id' | '/queries/$id'
  id: '__root__' | '/' | '/queries' | '/hosts/$id' | '/queries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueriesRoute: typeof QueriesRouteWithChildren
  HostsIdRoute: typeof HostsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries/$id': {
      id: '/queries/$id'
      path: '/$id'
      fullPath: '/queries/$id'
      preLoaderRoute: typeof QueriesIdRouteImport
      parentRoute: typeof QueriesRoute
    }
    '/hosts/$id': {
      id: '/hosts/$id'
      path: '/hosts/$id'
      fullPath: '/hosts/$id'
      preLoaderRoute: typeof HostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QueriesRouteChildren {
  QueriesIdRoute: typeof QueriesIdRoute
}

const QueriesRouteChildren: QueriesRouteChildren = {
  QueriesIdRoute: QueriesIdRoute,
}

const QueriesRouteWithChildren =
  QueriesRoute._addFileChildren(QueriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueriesRoute: QueriesRouteWithChildren,
  HostsIdRoute: HostsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
